name: Commit to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yml
    permissions:
      contents: read
      security-events: write
  test:
    name: Test
    uses: ./.github/workflows/playwright.yml
  general-lint:
    name: General Linting
    uses: ./.github/workflows/general-lint.yml
  build-docs:
    name: Build Docs
    uses: ./.github/workflows/docs-build.yml
    needs:
      - eslint
      - test
      - build
      - general-lint
  deploy-docs:
    name: Deploy Docs
    uses: ./.github/workflows/docs-deploy.yml
    permissions:
      pages: write
      id-token: write
    needs:
      - build-docs
  release-package:
    name: Release Package
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
      pull-requests: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs:
      - build-docs
