name: Commit to Main

on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yml
    permissions:
      contents: read
      security-events: write
  test:
    name: Test
    uses: ./.github/workflows/playwright.yml
  build-docs:
    name: Build Docs
    uses: ./.github/workflows/docs-build.yml
    needs:
      - eslint
      - test
