name: Build Docs

on:
  workflow_call:

jobs:
  build-docs:
    name: Building Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Deps
        run: npm ci
      - name: Build Docs
        run: npm run docs:gen
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: Docs
          path: man/
          if-no-files-found: error
          retention-days: 7
          compression-level: 9
