name: ESLint

on:
  workflow_call:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install Deps
        run: npm ci
      - name: Run ESLint
        run: npm run lint:eslint:sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@8f1a6fed33af5212fab8a999d004627ae8901d1b # v3.25.9
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
